<a href="https://colab.research.google.com/github/Noum3n/ds_bootcamp/blob/master/DS_bootcamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('hello colab')

hello colab


### Podstawy

In [ ]:
import numpy as np
np.__version__

'1.18.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D array (tablica)

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.2, 2.3, 4.5])
print(x)

[1.2 2.3 4.5]


In [ ]:
x.dtype

dtype('float64')

2D Array

In [ ]:
x = np.array([[1, 2], [-3, 4]])


In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[1, 2, 3], [2, 3, 4]])
print(x)

[[1 2 3]
 [2 3 4]]


In [ ]:
x.shape

(2, 3)

3D Array

In [ ]:
x = np. array(
    [[[1, 2, 3],
     [2, 3, 4]],

     [[5, 6, 8],
      [8, 7, 6]]]
)
x

array([[[1, 2, 3],
        [2, 3, 4]],

       [[5, 6, 8],
        [8, 7, 6]]])

In [ ]:
x.ndim

3

paremetr shape informuje nas ze mamy dwie tablice, dwa wiersza i trzy kolumny - 3d

In [ ]:
x.shape

(2, 2, 3)

### Typy danych

In [2]:
import numpy as np

In [5]:
A = np.array([2.1, 3.0, 4.3])
A.dtype

dtype('float64')

In [6]:
A = np.array([2, 3, 4], dtype='float')
A.dtype

dtype('float64')

In [7]:
A

array([2., 3., 4.])

In [8]:
A = np.array([2, 3, 4], dtype='complex')
A.dtype

dtype('complex128')

In [9]:
A

array([2.+0.j, 3.+0.j, 4.+0.j])

In [10]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [11]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

In [12]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

### Tworzenie tablic

In [13]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
np.ones(shape=(3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.full(shape=(5, 5), fill_value=4, dtype='int')

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [20]:
np.arange(start=10, stop=100, step=9)

array([10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [21]:
np.arange(start=100, stop=10, step=-9)

array([100,  91,  82,  73,  64,  55,  46,  37,  28,  19])

In [22]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [23]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [24]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
A.reshape((3, 5))


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

jeśli chcemy podać liczbę wierszy a python obliczy liczbę kolumn:

In [28]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

i w drugą stronę

In [29]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])