<a href="https://colab.research.google.com/github/Noum3n/ds_bootcamp/blob/master/DS_bootcamp/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('hello colab')

hello colab


### Podstawy

In [ ]:
import numpy as np
np.__version__

'1.18.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D array (tablica)

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.2, 2.3, 4.5])
print(x)

[1.2 2.3 4.5]


In [ ]:
x.dtype

dtype('float64')

2D Array

In [ ]:
x = np.array([[1, 2], [-3, 4]])


In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[1, 2, 3], [2, 3, 4]])
print(x)

[[1 2 3]
 [2 3 4]]


In [ ]:
x.shape

(2, 3)

3D Array

In [ ]:
x = np. array(
    [[[1, 2, 3],
     [2, 3, 4]],

     [[5, 6, 8],
      [8, 7, 6]]]
)
x

array([[[1, 2, 3],
        [2, 3, 4]],

       [[5, 6, 8],
        [8, 7, 6]]])

In [ ]:
x.ndim

3

paremetr shape informuje nas ze mamy dwie tablice, dwa wiersza i trzy kolumny - 3d

In [ ]:
x.shape

(2, 2, 3)

### Typy danych

In [ ]:
import numpy as np

In [ ]:
A = np.array([2.1, 3.0, 4.3])
A.dtype

dtype('float64')

In [ ]:
A = np.array([2, 3, 4], dtype='float')
A.dtype

dtype('float64')

In [ ]:
A

array([2., 3., 4.])

In [ ]:
A = np.array([2, 3, 4], dtype='complex')
A.dtype

dtype('complex128')

In [ ]:
A

array([2.+0.j, 3.+0.j, 4.+0.j])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

In [ ]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

### Tworzenie tablic

In [ ]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full(shape=(5, 5), fill_value=4, dtype='int')

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=9)

array([10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [ ]:
np.arange(start=100, stop=10, step=-9)

array([100,  91,  82,  73,  64,  55,  46,  37,  28,  19])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3, 5))


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

jeśli chcemy podać liczbę wierszy a python obliczy liczbę kolumn:

In [ ]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

i w drugą stronę

In [ ]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### Podstawowe operacje na tablicach

In [ ]:
import numpy as np

In [ ]:
A = np.array([1, 2, 3, 4])
B = np. array([3, -4, 5, 6])
print(A)
print(B)



[1 2 3 4]
[ 3 -4  5  6]


In [ ]:
A + B

array([ 4, -2,  8, 10])

In [ ]:
A - B

array([-2,  6, -2, -2])

In [ ]:
A * B

array([ 3, -8, 15, 24])

In [ ]:
A / B

array([ 0.33333333, -0.5       ,  0.6       ,  0.66666667])

In [ ]:
np.add(A, B)

array([ 4, -2,  8, 10])

In [ ]:
np.subtract(A, B)

array([-2,  6, -2, -2])

In [ ]:
np.multiply(A, B)

array([ 3, -8, 15, 24])

In [ ]:
A + 3

array([4, 5, 6, 7])

In [ ]:
A - 4

array([-3, -2, -1,  0])

In [ ]:
A + 3*B

array([ 10, -10,  18,  22])

In [ ]:
X = np.array([[1, 3], [4, 5]])
Y = np.array([[-1, 0], [3, 2]])

print(X, '\n')
print(Y)

[[1 3]
 [4 5]] 

[[-1  0]
 [ 3  2]]


mnożenie macierzowe (wiersz razy kolumna). Trzy metody:

In [ ]:
np.dot(X, Y)

array([[ 8,  6],
       [11, 10]])

In [ ]:
X.dot(Y)

array([[ 8,  6],
       [11, 10]])

In [ ]:
Y.dot(X)

array([[-1, -3],
       [11, 19]])

In [ ]:
X @ Y

array([[ 8,  6],
       [11, 10]])

### Generowanie liczb pseudolosowych

In [ ]:
np.random.seed(0)

In [ ]:
np.random.rand()

0.5488135039273248

In [ ]:
np.random.randn(10)

array([ 0.74159174,  1.55291372, -2.2683282 ,  1.33354538, -0.84272405,
        1.96992445,  1.26611853, -0.50587654,  2.54520078,  1.08081191])

In [ ]:
np.random.randn(10, 4)

array([[ 0.48431215,  0.57914048, -0.18158257,  1.41020463],
       [-0.37447169,  0.27519832, -0.96075461,  0.37692697],
       [ 0.03343893,  0.68056724, -1.56349669, -0.56669762],
       [-0.24214951,  1.51439128, -0.3330574 ,  0.04736482],
       [ 1.46274045,  1.53502913,  0.56644004,  0.14926509],
       [-1.078278  ,  1.39547227,  1.78748405, -0.56951726],
       [ 0.17538653, -0.46250554, -1.0858006 ,  0.63973599],
       [-0.38586334, -0.77576235,  0.99571135, -1.93320478],
       [ 0.24853063, -0.03124534, -0.13947396, -0.19065598],
       [ 0.44863753, -0.99242977, -0.22593966, -1.65457077]])

funkcja rand zwróci wartość losową z przedziału 0-1:

In [ ]:
np.random.rand() 

0.24442559200160274

In [ ]:
np.random.rand(5, 3)

array([[0.15896958, 0.11037514, 0.65632959],
       [0.13818295, 0.19658236, 0.36872517],
       [0.82099323, 0.09710128, 0.83794491],
       [0.09609841, 0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552, 0.73926358]])

funkcja randint zwróci wartość nieujemną mniejszą niż zadany parametr, lub przedział:

In [ ]:
np.random.randint(10)

0

In [ ]:
np.random.randint(low=4, high= 20, size=10)

array([ 6, 15, 14, 19, 11, 15,  6, 13,  6, 18])

In [ ]:
np.random.choice([2, 4, 4, 5, 6, 7, 8, 4])

5

In [ ]:
np.random.choice(['python', 'java', 'r', 'sql'])

'r'

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)

In [ ]:
data

array([0, 5, 7, 8, 1, 4, 9, 6, 2, 3])

### Podstawowe funkcje w numpy

funkcja exponent często wykorzystywana w sieciach neuronowych:

In [ ]:
np.exp(1)

2.718281828459045

sqrt zwróci pierwiastek kwadratowy z przekazanej liczby:

In [ ]:
np.sqrt(9)

3.0

funkcja all przechodzi przez każdy element i sprawdza wartość logiczną. Jeśli którykolwiek element ma wartość F, całość jest False:

In [ ]:
np.all([2, 3, 0])

False

In [ ]:
np.any([0, 0, 0])

False

jak wyciągnąć indeks z tablicy o największej wartości a następnie ją wyciąć?:

In [ ]:
A = np.random.rand(5)
A

array([0.64717414, 0.84138612, 0.26473016, 0.39782075, 0.55282148])

In [ ]:
np.argmax(A)

1

In [ ]:
A[np.argmax(A)]

0.8413861191973544

In [ ]:
np.argmin(A)

2

In [ ]:
np.argsort(A)

array([2, 3, 4, 0, 1])

In [ ]:
np.max(A)

0.8413861191973544

In [ ]:
np.min(A)

0.26473016428344964

In [ ]:
np.mean(A)

0.540786531262912

In [ ]:
np.median(A)

0.5528214798875715

In [ ]:
np.std(A)

0.1992333341389904

### Indeksowanie, Wycinanie

In [1]:
import numpy as np  

In [4]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[idx], A[strat, stop], A[start], A[stop]

In [6]:
A[2]

2

In [7]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [8]:
A[:3]

array([0, 1, 2])

In [10]:
A[4:8]

array([4, 5, 6, 7])

In [11]:
A[[2, 5]]

array([2, 5])

In [12]:
A[-2]

18

In [13]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
# wycinanie wierszy
A[0]

array([0, 1, 2, 3, 4])

In [15]:
A[3]

array([15, 16, 17, 18, 19])

In [17]:
# wycinanie kolumn
A[:,0]

array([ 0,  5, 10, 15])

In [18]:
A[:, -1]

array([ 4,  9, 14, 19])

In [19]:
# wycinanie konkretnych elementów (współrzędne)
A[1, 3]

8

In [20]:
# wycinanie większych sekcji
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [22]:
# zamiana wyciętego elementu na inny
A[1, 2] = 40
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 40,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### Iteracja po tablicach

In [23]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 40,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
for row in A:
    print(row)

[0 1 2 3 4]
[ 5  6 40  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [25]:
for row in A:
    print(row[1])

1
6
11
16


In [26]:
for row in A:
    print(row[:2])

[0 1]
[5 6]
[10 11]
[15 16]


In [27]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
40
8
9
10
11
12
13
14
15
16
17
18
19


### zmiana rozmiaru tablic

In [28]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 40,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
A.shape

(4, 5)

In [31]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 40],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [32]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 40,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
# transponowanie macierzy czyli zamiana wierszy na kolumny i kolumn na wiersze
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 40, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### maski logiczne

In [36]:
A = np.arange(start= -10, stop= 10, step= 0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [37]:
# maski logiczne służą do wyszukiwania i wycinania określonych danych np wartości dodatnich
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [38]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [39]:
# można też łączyć różne warunki dla masek
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [40]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [43]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [44]:
A[np.bitwise_or(A < -5, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])