<a href="https://colab.research.google.com/github/Noum3n/ds_bootcamp/blob/master/DS_bootcamp/02_Algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algebra Liniowa

### Norma wektora, długość wektora w R2


In [1]:
import numpy as np
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [2]:
np.linalg.norm(v1)

4.123105625617661

### Norma euklidesowa w Rn

In [3]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

### odległość dwóch punktów na płaśzczyźnie

In [5]:
# przykład poniższy to trójkąt prostokątny gdzie p i q to wierzchołki a długość wektora to przeciwprostokątna.
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

### odległość dwóch punkótw w przestrzeni Rn

In [6]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

### mnożenie macierzy

In [11]:
# warunkiem mnożenia macierzy jest ta sama liczba wierszy w pierwszej co kolumn w drugiej
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])

print(X)
print(Y)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [12]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [14]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [15]:
np.dot(X, Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

### wyznacznik macierzy

In [2]:
import numpy as np

A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10.0

In [4]:
# ślad macierzy to suma wartości na przekątnej
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

### macierz jednostkowa

In [5]:
# macierz kwadratowa, gdy na przekątnej są jedynki
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### macierz odwrotna

In [6]:
# taka macierz kwadratowa, że AB = BA = I (macierz jednostkowa)
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [7]:
# jeśi chcemy sprawdzić to musimy pomnożyć macierz A i B ale trzeba ustawić stopień precyzji, żeby nie było ułamków
np.set_printoptions(precision=4, suppress= True)

np.dot( A, B)

array([[1., 0.],
       [0., 1.]])

In [8]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

### macierz transponowana

In [9]:
# wiersze zamienia na kolumny
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [10]:
A.T

array([[ 2, -1],
       [ 4,  3]])

### rozwiązywanie układów równań

In [11]:
# jeśli liczba równań = liczbie niewiadomych jak w przykładzie:
# 2x + 4y = 10 i x - y = -1 to możemy tak:
# A = macierz współczynników, B = macierz wyrazów wolnych, X = macierz niewiadomych
A = np.array([[2, 4], [1, -1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [12]:
B = np.array([[10], [-1]])
B

array([[10],
       [-1]])

In [13]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [ ]:
# rozwiązaniem równania jest 1 i 2
# analogicznie dla 100 niewiadomych i 100 równań